// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUwDPlbVd8OzZrVy_3iWm5PAYu1a-vm2s',
    appId: '1:626568914227:web:fdd05df23cc59c63c1ca46',
    messagingSenderId: '626568914227',
    projectId: 'mind-labify',
    authDomain: 'mind-labify.firebaseapp.com',
    storageBucket: 'mind-labify.appspot.com',
    measurementId: 'G-3T55RYYNPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj1pvAXf8-9HgLZi645TjUrMJdU27tUxw',
    appId: '1:626568914227:android:c06a5b9d8bd6d0a7c1ca46',
    messagingSenderId: '626568914227',
    projectId: 'mind-labify',
    storageBucket: 'mind-labify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuc-lLay-ogzOLy26pRMlGOMXzGun15P4',
    appId: '1:626568914227:ios:d06a84d1d71eafeac1ca46',
    messagingSenderId: '626568914227',
    projectId: 'mind-labify',
    storageBucket: 'mind-labify.appspot.com',
    iosBundleId: 'com.mindlabify.app',
  );

}